repos:
- repo: https://github.com/ambv/black
  rev: 19.10b0
  hooks:
  - id: black

- repo: https://gitlab.com/pycqa/flake8
  rev: 3.8.1
  hooks:
  - id: flake8

- repo: https://github.com/timothycrosley/isort
  rev: 4.3.21
  hooks:
  - id: isort

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.0.1
  hooks:
  - id: check-docstring-first
  - id: check-yaml
  - id: debug-statements
  - id: end-of-file-fixer
  - id: trailing-whitespace

- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v0.770
  hooks:
  - id: mypy

- repo: https://github.com/asottile/setup-cfg-fmt
  rev: v1.9.0
  hooks:
  - id: setup-cfg-fmt

- repo: local
  hooks:
  - id: requirements
    name: Check Requirements
    language: system
    files: requirements\.(txt|in)$
    entry: make update-dependencies
